#brew
tap "homebrew/cask"
# alternativie cask versions such as nightly builds
tap "homebrew/cask-versions"

#packages
brew "ack"
brew "act"
brew "awscli"
brew "autopep8"
brew "bat"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "docker-machine-driver-xhyve"
brew "etheruem"
brew "fd"
brew "flake8"
brew "fzf"
brew "git-crypt"
brew "git-flow"
brew "gmp"
brew "heroku/brew/heroku"
brew "htop"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "libmemcached"
brew "ncdu"
brew "neovim"
brew "pipx"
brew "pkg-config"
brew "prettyping"
brew "python"
brew "pylint"
brew "ripgrep"
brew "shellcheck"
brew "sphinx-doc"
brew "ssh-copy-id"
brew "sslmate"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "unrar"
brew "vale"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"

# mac apps / automatically skipped on Linux
# need to apt install these on linux
cask "alacritty"
cask "alfred"
cask "authy"
cask "brave-browser"
cask "sequel-ace"
cask "docker"
cask "dropbox"
cask "firefox-nightly"
cask "figma-beta"
cask "font-fira-code"
cask "flux"
cask "iterm2-nightly"
cask "karabiner-elements"
cask "keepassx"
cask "keepassxc"
cask "macvim"
cask "mysql-shell"
cask "parallels"
cask "pgadmin4"
cask "postman"
cask "rescuetime"
cask "rstudio"
cask "tunnelblick"
cask "vscodium"
cask "sequel-pro-nightly"
cask "spotify"
cask "tower"
cask "vivaldi"

mas "Xcode", id: 497799835
mas "Evernote", id: 406056744
mas "Be Focused Pro", id: 961632517
